% Code generated by GiraffeTools
configuration = [];
tvm_design_constant(configuration);

configuration = [];
tvm_design_stimulus(configuration);

configuration = [];
tvm_design_highpassFilter(configuration);

configuration = [];
tvm_design_motionRegression(configuration);

configuration = [];
tvm_design_retroicor(configuration);

configuration = [];
tvm_design_retroicor(configuration);

configuration = [];
tvm_regressConfounds(configuration);

configuration = [];
tvm_realignFunctionals(configuration);

configuration = [];
tvm_smoothFunctionals(configuration);

configuration = [];
tvm_glm(configuration);

configuration = [];
tvm_glmToFMap(configuration);

configuration = [];
tvm_glmToTMap(configuration);

configuration = [];
tvm_retroicorBackProject(configuration);

configuration = [];
tvm_movieFrom4D(configuration);

configuration = [];
tvm_reconAll(configuration);

configuration = [];
tvm_useBbregister(configuration);

configuration = [];
tvm_volumeWithBoundariesToMovie(configuration);

configuration = [];
tvm_volumeWithBoundariesToMovie(configuration);

configuration = [];
tvm_recursiveBoundaryRegistration(configuration);

configuration = [];
tvm_boundariesToObj(configuration);

configuration = [];
tvm_makeLevelSet(configuration);

configuration = [];
tvm_laplacePotentials(configuration);

configuration = [];
tvm_gradient(configuration);

configuration = [];
tvm_computeDivergence(configuration);

configuration = [];
tvm_levelSetToObj(configuration);

configuration = [];
tvm_objToBoundary(configuration);

configuration = [];
tvm_volumeWithBoundariesToMovie(configuration);

configuration = [];
tvm_designMatrixToTimeCourse(configuration);

configuration = [];
tvm_volumetricLayering(configuration);

configuration = [];
tvm_roiToDesignMatrix(configuration);

configuration = [];
configuration.i_FunctionalFolder = 'Scans/Functional/Realigned/';
configuration.o_DesignMatrix = 'DesignMatrix/design1.mat';
tvm_design_empty(configuration);

% end of script